### ISSUE TITLE
"ImportError: cannot import name BigO"

### ISSUE THREAD

**Issue by Cris-Moran** [Alfex4936/python-bigO-calculator#1]
Hello!

Using the Quicksort example in the README.md file gave me the following error:

`Traceback (most recent call last):
  File "bigO.py", line 1, in <module>
    from bigO import BigO
  File "/Users/cris.moran/Dev/BigO/src/bigO.py", line 1, in <module>
    from bigO import BigO
ImportError: cannot import name BigO`

I thought this was initially a problem with the virtualenv I was using but the error also arose when I installed the package globally.

I'm not too experienced with Python packages so I'm not really sure what is causing this... does anyone know how to fix this?

**Comment by Alfex4936** [comment]
Hello!

First, make sure you installed the latest version of this package and it seems that you're working on a file named "bigO.py",

If so, you should not use the same name of the package for your files, because there is no BigO class in your working "bigO.py" file.

You can try after renaming your file and please let me know if this still doesn't work!
